import os
import json
import matplotlib.pyplot as plt

'''
Script 03:
This script plots averaged MTF curves from the summary JSON files generated by the averaging scripts (e.g. 02_average_metrics.py).

The output is a set of .jpg figures saved in the `analysis_dir`, showing
the MTF curves for each color channel (R, G, B) and the luminance channel (Y).

Adjust the y-axis range in:
      plt.ylim(0, 1.5)
    depending on your data’s MTF values.
Set necessary variables under CONFIGURATION (source, summary_dir, split type, output_dir) and run:
    python 03_plotMTFcurve.py
'''
# CONFIGURATION
source  = "Dataset"
summary_dir = f"/Users/kimiaarfaie/Github/Image-Information-Metrics-in-Machine-Vision-Systems/Metric_Analysis/Metrics/{source}/Average Metrics+1"
imatest_summary_path = summary_dir
output_dir = f"/Users/kimiaarfaie/Github/Image-Information-Metrics-in-Machine-Vision-Systems/Metric_Analysis/Metrics/{source}/MTF_curves"
analysis_dir = output_dir
os.makedirs(analysis_dir, exist_ok=True)

ISOfocuse_split = [["100ISO", "Focused"], ["1600ISO", "Focused"], ["6400ISO", "Focused"], ["25600ISO", "Focused"]]
size_split = [["18.0 mm", "Dist1"], ["18.0 mm", "Dist2"], ["55.0 mm", "Dist1"], ["55.0 mm", "Dist2"]]
ISO_split = [["100ISO"], ["1600ISO"], ["6400ISO"], ["25600ISO"]]
Focused_split = [["Focused"], ["Defocus1"], ["Defocus2"]]
EV_split = [["-3EV"], ["-2EV"], ["-1EV"], ["0EV"], ["+1EV"]]

splits = Focused_split

# ---- PER SPLIT MTF PLOTS ONLY ----
for split in splits:
    summary_file = split.replace(" ", "").replace(".", ".") + "_average_summary.json"
    summary_path = os.path.join(imatest_summary_path, summary_file)

    if not os.path.exists(summary_path):
        print(f"Missing summary for {split}")
        continue

    with open(summary_path, 'r') as f:
        data = json.load(f)

    freq1 = data.get("freq1", [])
    freq_unit = data.get("freq1units", "cycles/pixel")

    plt.figure()
    ax = plt.gca()
    ax.tick_params(labelsize=14)
    for k, color, style, width in zip(
        ["mtf_r", "mtf_g", "mtf_b", "mtf_y"],
        ["r", "g", "b", "k"],
        ["--", "--", "--", "-"],
        [1.0, 1.0, 1.0, 2.0]
    ):
        vec = data.get(k, [])
        if vec:
            plt.plot(freq1[:len(vec)], vec, label=k, color=color, linestyle=style, linewidth=width)

    plt.xlabel(f"Frequency ({freq_unit})", fontsize=18)
    plt.xlim(0, 0.5)
    plt.ylim(0, 1.5) # change this depending on MTF range
    plt.ylabel("MTF", fontsize=18)
    plt.legend(fontsize=18)
    plt.grid(True)
    plt.tight_layout()

    ax = plt.gca()
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    plt.savefig(os.path.join(analysis_dir, f"mtf_{split}.jpg"), dpi=300)
    plt.close()
